wandb_version: 1

learning_rate:
  desc: null
  value: 2.0e-05
dataset:
  desc: null
  value: LibriSpeech
epochs:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.17.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1720825767
    t:
      1:
      - 1
      - 2
      - 3
      - 15
      - 50
      - 55
      2:
      - 1
      - 2
      - 3
      - 15
      - 50
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.9
      5: 0.17.4
      8:
      - 3
      - 5
      13: windows-amd64
