_wandb:
    value:
        cli_version: 0.17.4
        python_version: 3.10.9
        t:
            1:
                - 1
                - 2
                - 3
                - 15
                - 50
                - 55
            2:
                - 1
                - 2
                - 3
                - 15
                - 50
                - 55
            3:
                - 13
                - 16
                - 23
                - 55
            4: 3.10.9
            5: 0.17.4
            8:
                - 3
                - 5
            12: 0.17.4
            13: windows-amd64
dataset:
    value: LibriSpeech
epochs:
    value: 1
learning_rate:
    value: 2e-05
